### PR TITLE
Accept nil targetRelease on executing command, just omit hooks part

### LINKED ISSUE #565: Helmsman fails on deleting untracked release
For plan with:
```2021-01-04 14:04:55 NOTICE: -------- PLAN starts here --------------
2021-01-04 14:04:55 WARNING: Untracked release [ filebeat ] found and it will be deleted -- priority: -1000
```

results in

```2021-01-04 14:04:55 INFO: Printing the commands of the current plan ...
helm uninstall filebeat --namespace filebeat
2021-01-04 14:04:55 INFO: Sorting the commands in the plan based on priorities (order flags) ... 
2021-01-04 14:04:55 INFO: Executing plan
2021-01-04 14:04:55 ERROR: nil target release
```

because helmRelease uninstall command does not defines targetRelease considered hard dependency for releaseWithHooks function

### PR DESCRIPTION
**Pull request by mkubaczyk**
Should fix #565 

I can't remember why there was such if statement on the beginning of releaseWithHooks function so I'll wait for review.

I've just wrapped before and after hooks parts in IF statement so the main cmdExec can be invoked even if targetRelease is nil (like for removing untracked release)

### CODE REVIEW

File: internal/app/plan.go [hunk 1]
```diff
@@ -135,47 +135,45 @@ func releaseWithHooks(cmd orderedCommand, storageBackend string, wg *sync.WaitGr
...
-	}
 	var annotations []string
-	for _, c := range cmd.beforeCommands {
-		if err := execOne(c.Command, cmd.targetRelease); err != nil {
-			errors <- err
+	if cmd.targetRelease != nil && !flags.destroy {
+		for _, c := range cmd.beforeCommands {
+			if err := execOne(c.Command, cmd.targetRelease); err != nil {
+				errors <- err
+				if key, err := c.getAnnotationKey(); err != nil {
```
Comment (luisdavim) [inline internal/app/plan.go:143]: I know this wasn't introduced by this PR but I think this is wrong, when `getAnnotationKey` returns a non `nil` error, the `key` will be empty, so we should only append the annotation if the error is `nil` right? Or am I missing something?

File: internal/app/plan.go [hunk 2]
```diff
@@ -135,47 +135,45 @@ func releaseWithHooks(cmd orderedCommand, storageBackend string, wg *sync.WaitGr
...
+					annotations = append(annotations, key+"=failed")
+				}
+				log.Verbose(err.Error())
+				return
+			}
 			if key, err := c.getAnnotationKey(); err != nil {
-				annotations = append(annotations, key+"=failed")
+				annotations = append(annotations, key+"=ok")
```
Comment (luisdavim) [inline internal/app/plan.go:150]: same as above, we can't append the annotation if the key is empty....

File: internal/app/plan.go [hunk 3]
```diff
@@ -135,47 +135,45 @@ func releaseWithHooks(cmd orderedCommand, storageBackend string, wg *sync.WaitGr
...
+			if err := execOne(c.Command, cmd.targetRelease); err != nil {
+				errors <- err
+				if key, err := c.getAnnotationKey(); err != nil {
+					annotations = append(annotations, key+"=failed")
+				}
+				log.Verbose(err.Error())
+			} else {
+				if key, err := c.getAnnotationKey(); err != nil {
+					annotations = append(annotations, key+"=ok")
+				}
```
Comment (luisdavim) [inline internal/app/plan.go:176]: same here...

**Review by luisdavim — COMMENTED** [review]
Your changes LGTM but I think we have a problem when appending the annotations that you could also address in this PR.

**Comment by luisdavim** [comment]
I've opened https://github.com/Praqma/helmsman/pull/568 to address my comments there.
